In [1]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv('score.sc',header=0, sep='\s+')
print list(df)
#df['all_cst']

['total_score', 'fa_rep', 'hbond_sc', 'all_cst', 'tot_pstat_pm', 'tot_nlpstat_pm', 'tot_burunsat_pm', 'tot_hbond_pm', 'tot_NLconts_pm', 'tot_nlsurfaceE_pm', 'tot_total_charge', 'tot_total_pos_charges', 'tot_total_neg_charges', 'tot_seq_recovery', 'SR_1', 'SR_1_total_score', 'SR_1_fa_rep', 'SR_1_hbond_sc', 'SR_1_all_cst', 'SR_1_hbond_pm', 'SR_1_burunsat_pm', 'SR_1_pstat_pm', 'SR_1_nlpstat_pm', 'SR_2', 'SR_2_total_score', 'SR_2_fa_rep', 'SR_2_hbond_sc', 'SR_2_all_cst', 'SR_2_hbond_pm', 'SR_2_burunsat_pm', 'SR_2_pstat_pm', 'SR_2_nlpstat_pm', 'SR_3', 'SR_3_total_score', 'SR_3_fa_rep', 'SR_3_hbond_sc', 'SR_3_all_cst', 'SR_3_hbond_pm', 'SR_3_burunsat_pm', 'SR_3_pstat_pm', 'SR_3_nlpstat_pm', 'SR_4', 'SR_4_total_score', 'SR_4_fa_rep', 'SR_4_hbond_sc', 'SR_4_all_cst', 'SR_4_hbond_pm', 'SR_4_burunsat_pm', 'SR_4_pstat_pm', 'SR_4_nlpstat_pm', 'SR_5', 'SR_5_total_score', 'SR_5_fa_rep', 'SR_5_hbond_sc', 'SR_5_all_cst', 'SR_5_interf_E_1_2', 'SR_5_dsasa_1_2', 'SR_5_hbond_pm', 'SR_5_burunsat_pm', 'Transform_accept_ratio', 'allcst', 'description']

In [3]:
interfcst = 'SR_5_interf_E_1_2'
cst_filtered = df[ df.allcst < 5 ]
lowetotalscore = cst_filtered.sort_values('total_score').head(10)
lowetotalscore.sort_values(interfcst)[['description','allcst','total_score',interfcst]]

       description  allcst  total_score  SR_5_interf_E_1_2
8   1h2j.dock_0009    0.07      -401.33              -6.59
9   1h2j.dock_0010    0.11      -397.56              -6.48
18  1h2j.dock_0019    0.07      -398.17              -6.44
17  1h2j.dock_0018    0.08      -398.69              -5.73
5   1h2j.dock_0006    0.06      -398.23              -5.72
19  1h2j.dock_0020    0.19      -398.54              -5.68
16  1h2j.dock_0017    0.06      -395.68              -5.44
4   1h2j.dock_0005    0.06      -403.55              -5.40
12  1h2j.dock_0013    0.07      -396.90              -5.31
6   1h2j.dock_0007    0.06      -404.60              -3.52

In [10]:
print list(df)
df[['all_cst','SR_1_all_cst','SR_2_all_cst','SR_3_all_cst','SR_4_all_cst','description','SR_4_all_cst','total_score']]

['total_score', 'fa_rep', 'hbond_sc', 'all_cst', 'tot_pstat_pm', 'tot_nlpstat_pm', 'tot_burunsat_pm', 'tot_hbond_pm', 'tot_NLconts_pm', 'tot_nlsurfaceE_pm', 'tot_total_charge', 'tot_total_pos_charges', 'tot_total_neg_charges', 'tot_seq_recovery', 'SR_1', 'SR_1_total_score', 'SR_1_fa_rep', 'SR_1_hbond_sc', 'SR_1_all_cst', 'SR_1_hbond_pm', 'SR_1_burunsat_pm', 'SR_1_pstat_pm', 'SR_1_nlpstat_pm', 'SR_2', 'SR_2_total_score', 'SR_2_fa_rep', 'SR_2_hbond_sc', 'SR_2_all_cst', 'SR_2_hbond_pm', 'SR_2_burunsat_pm', 'SR_2_pstat_pm', 'SR_2_nlpstat_pm', 'SR_3', 'SR_3_total_score', 'SR_3_fa_rep', 'SR_3_hbond_sc', 'SR_3_all_cst', 'SR_3_hbond_pm', 'SR_3_burunsat_pm', 'SR_3_pstat_pm', 'SR_3_nlpstat_pm', 'SR_4', 'SR_4_total_score', 'SR_4_fa_rep', 'SR_4_hbond_sc', 'SR_4_all_cst', 'SR_4_interf_E_1_2', 'SR_4_dsasa_1_2', 'SR_4_hbond_pm', 'SR_4_burunsat_pm', 'Grid_score', 'Transform_accept_ratio', 'description']

,all_cst,SR_1_all_cst,SR_2_all_cst,SR_3_all_cst,SR_4_all_cst,description,SR_4_all_cst,total_score
0,0.0,0.00,0.00,0.0,0.00,2jie.dock_0001,0.00,505.45
1,0.0,0.00,0.00,0.0,0.00,2jie.dock_0002,0.00,451.19
2,0.0,0.01,0.01,0.0,0.01,2jie.dock_0003,0.01,435.68
3,0.0,0.05,0.05,0.0,0.05,2jie.dock_0004,0.05,467.65
4,0.0,0.02,0.02,0.0,0.02,2jie.dock_0005,0.02,497.61
5,0.0,0.00,0.00,0.0,0.00,2jie.dock_0006,0.00,453.99
6,0.0,0.03,0.03,0.0,0.03,2jie.dock_0007,0.03,455.60
7,0.0,0.07,0.07,0.0,0.07,2jie.dock_0008,0.07,511.47
8,0.0,0.03,0.03,0.0,0.03,2jie.dock_0009,0.03,461.24