In [1]:
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

In [2]:
df = pd.read_csv('score.sc',header=0, sep='\s+')
print list(df)

['total_score', 'fa_rep', 'hbond_sc', 'all_cst', 'tot_pstat_pm', 'tot_nlpstat_pm', 'tot_burunsat_pm', 'tot_hbond_pm', 'tot_NLconts_pm', 'tot_nlsurfaceE_pm', 'tot_total_charge', 'tot_total_pos_charges', 'tot_total_neg_charges', 'tot_seq_recovery', 'SR_1', 'SR_1_total_score', 'SR_1_fa_rep', 'SR_1_hbond_sc', 'SR_1_all_cst', 'SR_1_hbond_pm', 'SR_1_burunsat_pm', 'SR_1_pstat_pm', 'SR_1_nlpstat_pm', 'SR_2', 'SR_2_total_score', 'SR_2_fa_rep', 'SR_2_hbond_sc', 'SR_2_all_cst', 'SR_2_hbond_pm', 'SR_2_burunsat_pm', 'SR_2_pstat_pm', 'SR_2_nlpstat_pm', 'SR_3', 'SR_3_total_score', 'SR_3_fa_rep', 'SR_3_hbond_sc', 'SR_3_all_cst', 'SR_3_hbond_pm', 'SR_3_burunsat_pm', 'SR_3_pstat_pm', 'SR_3_nlpstat_pm', 'SR_4', 'SR_4_total_score', 'SR_4_fa_rep', 'SR_4_hbond_sc', 'SR_4_all_cst', 'SR_4_hbond_pm', 'SR_4_burunsat_pm', 'SR_4_pstat_pm', 'SR_4_nlpstat_pm', 'SR_5', 'SR_5_total_score', 'SR_5_fa_rep', 'SR_5_hbond_sc', 'SR_5_all_cst', 'SR_5_hbond_pm', 'SR_5_burunsat_pm', 'SR_5_pstat_pm', 'SR_5_nlpstat_pm', 'SR_6', 'SR_6_total_score', 'SR_6_fa_rep', 'SR_6_hbond_sc', 'SR_6_all_cst', 'SR_6_hbond_pm', 'SR_6_burunsat_pm', 'SR_6_pstat_pm', 'SR_6_nlpstat_pm', 'SR_7', 'SR_7_total_score', 'SR_7_fa_rep', 'SR_7_hbond_sc', 'SR_7_all_cst', 'SR_7_interf_E_1_2', 'SR_7_dsasa_1_2', 'SR_7_hbond_pm', 'SR_7_burunsat_pm', 'Transform_accept_ratio', 'allcst', 'description']

In [3]:
interfcst = 'SR_7_interf_E_1_2'
cst_filtered = df[ df.allcst < 5 ]
lowetotalscore = cst_filtered.sort_values('total_score').head(10)
lowetotalscore.sort_values(interfcst)[['description','allcst','total_score',interfcst]]

       description  allcst  total_score  SR_7_interf_E_1_2
12  1jcl.dock_0013    1.20      -350.06              -6.28
9   1jcl.dock_0010    3.52      -353.77              -4.60
0   1jcl.dock_0001    2.34      -347.57              -3.42
2   1jcl.dock_0003    1.94      -357.28              -2.99
18  1jcl.dock_0019    1.15      -349.28              -1.85
4   1jcl.dock_0005    0.52      -346.12              -1.38
7   1jcl.dock_0008    1.14      -349.01              -1.09
5   1jcl.dock_0006    1.69      -349.06              -0.98
19  1jcl.dock_0020    0.58      -347.07              -0.22
17  1jcl.dock_0018    0.78      -352.72              -0.17

In [6]:
#print list(df)
df[['allcst','SR_1_all_cst','SR_2_all_cst','SR_3_all_cst','SR_4_all_cst','description','SR_4_all_cst','total_score']].sort_values(['allcst'])

,allcst,SR_1_all_cst,SR_2_all_cst,SR_3_all_cst,SR_4_all_cst,description,SR_4_all_cst,total_score
11,0.07,0.03,0.03,0.00,0.00,1hqd.dock_0012,0.00,-369.64
5,0.36,0.08,0.08,0.00,0.00,1hqd.dock_0006,0.00,-360.43
19,0.48,0.10,0.10,0.00,0.00,1hqd.dock_0020,0.00,-365.34
8,0.50,0.25,0.25,0.00,0.00,1hqd.dock_0009,0.00,-359.61
1,0.51,0.13,0.13,0.01,0.01,1hqd.dock_0002,0.01,-373.06
3,0.64,0.13,0.13,0.01,0.01,1hqd.dock_0004,0.01,-352.27
13,0.87,0.14,0.14,0.00,0.00,1hqd.dock_0014,0.00,-372.02
10,0.91,0.18,0.18,0.00,0.00,1hqd.dock_0011,0.00,-371.04
17,0.92,0.19,0.19,0.00,0.00,1hqd.dock_0018,0.00,-369.06
18,0.96,0.43,0.43,0.03,0.03,1hqd.dock_0019,0.03,-367.59
12,1.09,0.54,0.54,0.03,0.03,1hqd.dock_0013,0.03,-369.66
0,1.50,0.30,0.30,0.01,0.01,1hqd.dock_0001,0.01,-355.80
6,1.70,0.85,0.85,0.00,0.00,1hqd.dock_0007,0.00,-366.39
4,1.86,0.93,0.93,0.00,0.00,1hqd.dock_0005,0.00,-372.64
9,7.02,2.70,2.70,0.00,0.00,1hqd.dock_0010,0.00,-351.11
7,7.10,2.46,2.46,0.00,0.00,1hqd.dock_0008,0.00,-358.71
16,7.58,2.32,2.32,0.00,0.00,1hqd.dock_0017,0.00,-348.36
14,7.77,2.83,2.83,0.01,0.01,1hqd.dock_0015,0.01,-345.71
2,10.09,3.09,3.09,0.00,0.00,1hqd.dock_0003,0.00,-347.40
15,10.12,3.18,3.18,0.00,0.00,1hqd.dock_0016,0.00,-344.72